import { AddressObjectViewModel } from '@type/address'

export type RegulationRM = {
	type: string
	name: string
	url: string
}

export type AuthTokenModel = {
	username: string
	password: string
}

export type CheckPhoneRM = {
	codeLength: number
	expirationDate: string | null
}

export type CheckPhoneVM = {
	tokenProviderId: number
	phone: string
}

export type RegisterEntityV2 = {
	phone: string
	code: string
	name: string
	surname: string
	isMale: boolean | null
	userAgent: string
	address?: AddressObjectViewModel
}

export type RecognizeAddress = {
	address: string
}

export type RegisterEntity = {
	phone: string
	name: string
	surname: string
	patronymic: string
	isMale: boolean
	password: string
	confirmPassword: string
	referral: string
	checkCodeForAutoGeneratedUser: string
	userAgent: string
}
